CREATE TABLE IF NOT EXISTS sneakers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    brand VARCHAR(25) DEFAULT NULL,
    color VARCHAR(25) DEFAULT NULL,
    size VARCHAR(25) DEFAULT NULL,
    price FLOAT DEFAULT 0
);  